# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

decode_s_attribute <- function(corpus, s_attribute, registry) {
    .Call('polmineR_Rcpp_decode_s_attribute', PACKAGE = 'polmineR.Rcpp', corpus, s_attribute, registry)
}

get_count_vector <- function(corpus, p_attribute, registry) {
    .Call('polmineR_Rcpp_get_count_vector', PACKAGE = 'polmineR.Rcpp', corpus, p_attribute, registry)
}

get_region_matrix <- function(corpus, s_attribute, strucs, registry) {
    .Call('polmineR_Rcpp_get_region_matrix', PACKAGE = 'polmineR.Rcpp', corpus, s_attribute, strucs, registry)
}

get_cbow_matrix <- function(corpus, p_attribute, registry, matrix, window) {
    .Call('polmineR_Rcpp_get_cbow_matrix', PACKAGE = 'polmineR.Rcpp', corpus, p_attribute, registry, matrix, window)
}

regions_to_ids <- function(corpus, p_attribute, registry, matrix) {
    .Call('polmineR_Rcpp_regions_to_ids', PACKAGE = 'polmineR.Rcpp', corpus, p_attribute, registry, matrix)
}

regions_to_count_matrix <- function(corpus, p_attribute, registry, matrix) {
    .Call('polmineR_Rcpp_regions_to_count_matrix', PACKAGE = 'polmineR.Rcpp', corpus, p_attribute, registry, matrix)
}

